export const UPDATE_INGREDIENT = "UPDATE_INGREDIENT";
export const UPDATE_SIZE = "UPDATE_SIZE";
export const UPDATE_PRICE = "UPDATE_PRICE";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_PRICES = "SET_PRICES";
export const RESET_PRICE = "RESET_PRICE";
export const FETCH_FAILED = "FETCH_FAILED";

export const PURCHASE_PIZZA_START = "PURCHASE_PIZZA_START";
export const PURCHASE_PIZZA_SUCCESS = "PURCHASE_PIZZA_SUCCESS";
export const PURCHASE_PIZZA_FAIL = "PURCHASE_PIZZA_FAIL";
export const PURCHASE_SPECIALTY_START = "PURCHASE_SPECIALTY_START";
export const PURCHASE_SPECIALTY_SUCCESS = "PURCHASE_SPECIALTY_SUCCESS";
export const PURCHASE_SPECIALTY_FAIL = "PURCHASE_SPECIALTY_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";
export const CLEAR_ORDERS = "CLEAR_ORDERS";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_REDIRECT_PATH = "AUTH_REDIRECT_PATH";

export const FETCH_SPECIALTY_PIZZAS_START = "FETCH_SPECIALTY_PIZZAS_START";
export const FETCH_SPECIALTY_PIZZAS_SUCCESS = "FETCH_SPECIALTY_PIZZAS_SUCCESS";
export const FETCH_SPECIALTY_PIZZAS_FAIL = "FETCH_SPECIALTY_PIZZAS_FAIL";
