export const UPDATE_INGREDIENT = "UPDATE_INGREDIENT";
export const UPDATE_SIZE = "UPDATE_SIZE";
export const UPDATE_PRICE = "UPDATE_PRICE";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_PRICES = "SET_PRICES";
export const FETCH_FAILED = "FETCH_FAILED";
